---
# vars file for citus-coordinator-conf
psql_scripts_citus_path: "/usr/bin"
citus_dbname: citusdb
psql_packages:
  - postgresql-{{ psql_version }}-citus-{{ citus_version }}
citus_scripts:
  - citus-connect.sh
slave_ips:
  - "{{ hostvars['slave1']['private_ip'] }}"
  - "{{ hostvars['slave2']['private_ip'] }}"
