---
# tasks file for repmgr-standby-conf
- name: Copy repmgr scripts to the remote host
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ psql_scripts_repmgr_path }}"
    owner: root
    group: root
    mode: '0755'
  with_items: "{{ repmgr_scripts }}"
- name: Execute repmgr scripts for master
  block:
    - name: Repmgr common scripts for standby cluster
      vars:
        repmgr_sql_file: setup-repmgr.sql
      ansible.builtin.shell: |
        {{ psql_scripts_repmgr_path }}/repmgr-common.sh {{ psql_version }} {{ psql_bindir_path }} {{ psql_scripts_repmgr_path }}/{{ repmgr_sql_file }}
      args:
        chdir: /var/lib/postgresql
        executable: /bin/bash
    - name: Systemd restart PostgreSQL
      become: yes
      ansible.builtin.systemd_service:
        name: postgresql
        state: restarted
        enabled: true
