---
# tasks file for server-register
- name: Copy k3s server scripts to the remote host
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ k3s_server_scripts_path }}"
    mode: '0755'
  with_items: "{{ k3s_server_scripts }}"

- name: k3s server register
  block:
    - name: Exec server register script
      ansible.builtin.shell: |
        {{ k3s_server_scripts_path }}/server-register.sh {{ psql_k3s_datastore_uri }} {{ keepalived_virtual_ip }} {{ ansible_host }}
      args:
        executable: /bin/bash
    - name: Slurp file content from the specific host
      ansible.builtin.slurp:
        src: /var/lib/rancher/k3s/server/token
      delegate_to: server-1
      register: server_token

    - name: Send k3s token from server to all other server
      ansible.builtin.copy:
        content: "{{ server_token.content | b64decode }}"
        dest: /tmp/k3s-server-token
        mode: '0644'
      delegate_to: server-2
  when: "'server-1' in ansible_hostname"

- name: k3s server register
  block:
    - name: Exec register script for sidecard server
      ansible.builtin.shell: |
        {{ k3s_server_scripts_path }}/server-side-register.sh {{ psql_k3s_datastore_uri }} /tmp/k3s-server-token {{ keepalived_virtual_ip }} {{ ansible_host }}
      args:
        executable: /bin/bash
  when: "'server-1' not in ansible_hostname"
