---
# tasks file for server-register
- name: Copy k3s server scripts to the remote host
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ k3s_server_scripts_path }}"
    mode: '0755'
  with_items: "{{ k3s_server_scripts }}"

- name: Get k3s installed version
  ansible.builtin.command: k3s --version
  register: k3s_version_output
  changed_when: false
  ignore_errors: true

- name: k3s server register
  when: k3s_version_output.rc != 0 and hostvars[groups['server'][0]]['ansible_hostname'] in ansible_hostname
  block:
    - name: Exec server register script
      ansible.builtin.shell: |
        {{ k3s_server_scripts_path }}/server-register.sh {{ keepalived_virtual_ip }} {{ ansible_host }}
      args:
        executable: /bin/bash
    - name: Slurp file content from the specific host
      ansible.builtin.slurp:
        src: /var/lib/rancher/k3s/server/token
      delegate_to: server-1
      register: server_token

    - name: Send k3s token from server to all other server
      ansible.builtin.copy:
        content: "{{ server_token.content | b64decode }}"
        dest: /tmp/k3s-server-token
        mode: '0644'
      delegate_to: server-2

- name: k3s side server register
  when: k3s_version_output.rc != 0 and hostvars[groups['server'][0]]['ansible_hostname'] not in ansible_hostname
  block:
    - name: Exec register script for sidecard server
      ansible.builtin.shell: |
        {{ k3s_server_scripts_path }}/server-side-register.sh /tmp/k3s-server-token {{ keepalived_virtual_ip }} {{ api_endpoint }} {{ api_port }} {{ ansible_host }}
      args:
        executable: /bin/bash
