---
# tasks file for repmgr-configuration
- name: Install required packages
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  with_items: "{{ repmgr_packages }}"
- name: Copy repmgr.conf file for repmgr configuration from templates
  ansible.builtin.template:
    src: repmgr.conf.j2
    dest: "{{ psql_repmgr_conf_path }}"
    owner: root
    group: root
    mode: '0644'
- name: Copy repmgr scripts to the remote host
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ psql_scripts_repmgr_path }}"
    owner: root
    group: root
    mode: '0755'
  with_items: "{{ repmgr_scripts }}"
- name: Execute repmgr scripts for master and slave cluster
  block:
    - name: Repmgr common scripts for both master and slave cluster
      vars:
        repmgr_sql_file: setup-repmgr.sql
      ansible.builtin.shell: |
        {{ psql_scripts_repmgr_path }}/repmgr-common.sh {{ psql_version }} {{ private_ip }} {{ psql_scripts_repmgr_path }}/{{ repmgr_sql_file }}
      args:
        chdir: /var/lib/postgresql
        executable: /bin/bash
    - name: Systemd restart PostgreSQL
      become: yes
      ansible.builtin.systemd_service:
        name: postgresql
        state: restarted
        enabled: true
    - name: Repmgr primary scripts for master cluster
      ansible.builtin.shell: |
        {{ psql_scripts_repmgr_path }}/repmgr-primary.sh {{ psql_repmgr_conf_path }}
      args:
        chdir: /var/lib/postgresql
        executable: /bin/bash
      when: "'master' in ansible_hostname"
    - name: Repmgr standby scripts for slave cluster
      ansible.builtin.shell: |
        {{ psql_scripts_repmgr_path }}/repmgr-standby.sh {{ psql_version }} {{ hostvars['master1']['private_ip'] }} {{ psql_repmgr_conf_path }} {{ psql_data_directory_path }}
      args:
        chdir: /var/lib/postgresql
        executable: /bin/bash
      when: "'slave' in ansible_hostname"
