---
# defaults file for self-signed-cert
crt_name: k3s
crt_dir: /etc/haproxy/ssl
crt_path: "{{ crt_dir }}/{{ crt_name }}.pem"
crt_key_path: "{{ crt_dir }}/{{ crt_name }}.pem.key"
crt_scripts_path: /usr/bin

haproxy_conf_path: /etc/haproxy
haproxy_firewall_services_dir: /etc/firewalld/services
