---
# vars file for vault/impl-config
vault_cluster_addr: "https://{{ ansible_host }}:8201"
vault_api_addr: "https://{{ ansible_host }}:8200"

etcd_endpoint: "https://{{ hostvars['server']['ansible_host'] }}:2379"
vault_tls_dir: /opt/vault/tls
vault_data_dir: /opt/vault/data
vault_config_dir: /opt/vault/vault.d
vault_service_dir: /usr/lib/systemd/system

vault_config_templates:
  - vault.env
  - vault.hcl

vault_service_template: vault.service
vault_temp_dir_path: /tmp/vault
vault_operator_path: "{{ vault_temp_dir_path }}/operator_init.json"
