---
# vars file for vault/store-vault-secrets
vault_cluster_addr: "https://{{ ansible_host }}:8201"
vault_api_addr: "https://{{ ansible_host }}:8200"

vault_kv_path: "{{ env }}"
vault_secrets_path: "{{ env }}/vault/creds"  # Replace with your actual path
