---
- name: k3s-dependencies-setup
  hosts: all
  become: true
  become_user: root
  tasks:
    - name: Ping all nodes
      ansible.builtin.ping:
  roles:
    - role: ../../roles/k3s/common/dependencies
    - role: ../../roles/k3s/common/kennel-config
