---
# tasks file for dependencies
- name: Install PostgreSQL Debian OS
  block:
    - name: Install required packages
      ansible.builtin.apt:
        name: "{{ item }}"
        state: present
      with_items: "{{ common_packages }}"
    - name: Prepare PostgreSQL packages
      ansible.builtin.shell: |
        # PostgreSQL
        install -d /usr/share/postgresql-common/pgdg
        curl -o /usr/share/postgresql-common/pgdg/apt.postgresql.org.asc --fail https://www.postgresql.org/media/keys/ACCC4CF8.asc

        # Create the repository configuration file:
        sh -c 'echo "deb [signed-by=/usr/share/postgresql-common/pgdg/apt.postgresql.org.asc] https://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list'
      args:
        executable: /bin/bash
    - name: Upddate apt packages
      ansible.builtin.apt:
        update_cache: yes
    - name: Install required packages
      ansible.builtin.apt:
        name: "{{ item }}"
        state: present
      with_items: "{{ debian_psql_packages }}"
  when: ansible_facts['os_family'] == "Debian"

- name: Install PostgreSQL RedHat OS
  block:
    - name: Install required packages
      ansible.builtin.apt:
        name: "{{ item }}"
        state: present
      with_items: "{{ common_packages }}"
    - name: Prepare PostgreSQL packages
      ansible.builtin.shell: |
        # PostgreSQL
        # Install the repository RPM:
        dnf install -y https://download.postgresql.org/pub/repos/yum/reporpms/EL-9-x86_64/pgdg-redhat-repo-latest.noarch.rpm

        # Disable the built-in PostgreSQL module:
        dnf -qy module disable postgresql
      args:
        executable: /bin/bash
    - name: Upddate apt packages
      ansible.builtin.dnf:
        update_cache: yes
    - name: Install required packages
      ansible.builtin.dnf:
        name: "{{ item }}"
        state: present
      with_items: "{{ redhat_psql_packages }}"
  when: ansible_facts['os_family'] == "RedHat"

- name: Config PostgreSQL
  block:
    - name: Copy pg_hba.conf file for psql configuration from templates
      ansible.builtin.template:
        src: pg_hba.conf.j2
        dest: "{{ psql_conf_folder_path }}/pg_hba.conf"
        mode: '0755'
    - name: Set correct permissions on pg_hba.conf
      ansible.builtin.file:
        path: "{{ psql_conf_folder_path }}/pg_hba.conf"
        owner: postgres
        mode: '0755'
      become: true
    - name: Systemd restart PostgreSQL
      become: true
      ansible.builtin.systemd_service:
        name: postgresql
        state: restarted
        enabled: true
