---
# vars file for dependencies
# psql_version: 16
common_packages:
  - curl
  - ca-certificates
psql_packages:
  - postgresql-{{ psql_version }}
  - postgresql-{{ psql_version }}-repmgr
  - postgresql-contrib
