---
- name: pgbouncer-commmon-conf
  hosts: connection-pool
  become: true
  become_user: root
  tasks:
    - name: Ping all nodes
      ansible.builtin.ping:
  roles:
    - role: ../../roles/postgresql/pgbouncer/common
