---
# vars file for agent-register
k3s_agent_scripts:
  - agent-register.sh
  - kube-config-modify.sh
k3s_agent_scripts_path: "/usr/bin"
load_balancer_virtual_url: "https://{{ keepalived_virtual_ip }}:{{ load_balancer_port }}"
k3s_config_path: /home/vagrant/.kube/config
