---
# vars file for common
common_packages:
  - pgbouncer
pgbouncer_scripts_path: /usr/bin
pgbouncer_scripts:
  - pgbouner-ini-conf.sh
auth_user: "postgres"
db_host: "{{ hostvars['coordinator1']['private_ip'] }}"
db_name: "postgres"
db_port: "{{ docker_psql_port }}"
