---
# vars file for repmgr-configuration
# psql_version: 16
repmgr_packages:
  - postgresql-{{ psql_version }}-repmgr
psql_data_directory_path: "/var/lib/postgresql/{{ psql_version }}/main"
psql_repmgr_conf_path: "/etc/postgresql/{{ psql_version }}/main/repmgr.conf"
psql_bindir_path: "/usr/lib/postgresql/{{ psql_version }}/bin"
psql_scripts_repmgr_path: "/usr/bin"
repmgr_scripts:
  - repmgr-common.sh
  - repmgr-primary.sh
  - repmgr-standby.sh
  - setup-repmgr.sql
psql_conf_path:
  - /etc/postgresql/{{ psql_version }}/main/postgresql.conf
  - /etc/postgresql/{{ psql_version }}/main/pg_hba.conf
