---
# vars file for dependencies
debian:
  common_packages:
    - curl
    - ca-certificates
    - wireguard
    - gpg
    - wget
    - jq
  vault_packages:
    - vault

rhel:
  common_packages:
    - curl
    - ca-certificates
    - yum-utils
    - jq


centos:
  common_packages:
    - curl
    - ca-certificates
    - yum-utils
    - epel-release
    - jq
