---
all:
  hosts:
    coordinator1:
      ansible_host: 0.0.0.0
      ansible_port: 2751
    worker1:
      ansible_host: 0.0.0.0
      ansible_port: 2761
    worker2:
      ansible_host: 0.0.0.0
      ansible_port: 2762
  vars:
    psql_version: 15
    citus_version: 11.3
    master_server_ip: 192.168.10.11
    replica_server_ip: 192.168.10.21
    server_cidr_range: 192.168.10.0/24
    docker_network_cidr_range: 172.20.10.0/24
    docker_default_cidr_range: 172.17.0.0/16

  children:
    coordinator:
    worker:

coordinator:
  hosts:
    coordinator1:

worker:
  hosts:
    worker1:
    worker2:

repmgr:
  hosts:
    coordinator1:
    worker1:
    worker2:
