---
- name: k3s-agent-register-setup
  hosts: agent
  become: true
  become_user: root
  tasks:
    - name: Ping all nodes
      ansible.builtin.ping:
  roles:
    - role: ../../roles/k3s/agent/agent-register
