---
- name: keepalived-dependencies-setup
  hosts: server
  become: true
  become_user: root
  tasks:
    - name: Ping all nodes
      ansible.builtin.ping:
  roles:
    - role: ../../../../roles/k3s/load-balancer/haproxy/common
