---
all:
  hosts:
    server-1:
      ansible_host: 192.168.10.11
    server-2:
      ansible_host: 192.168.10.12
    agent-1:
      ansible_host: 192.168.10.21
    agent-2:
      ansible_host: 192.168.10.22
  vars:
    rhel_version: 9
    server_ip: 172.29.139.102
    psql_k3s_port: 5432
    psql_k3s_url: "{{ server_ip }}:{{ psql_k3s_port }}"
    psql_k3s_user: "k3s"
    psql_k3s_pass: "k3s"

  children:
    coordinator:
    worker:

coordinator:
  hosts:
    coordinator1:

worker:
  hosts:
    worker1:
