---
# vars file for dependencies
common_packages:
  - curl
  - ca-certificates
psql_packages:
  - postgresql-{{ psql_version }}
  # - postgresql-{{ psql_version }}-repmgr
  - postgresql-contrib
psql_conf_folder_path: "/etc/postgresql/{{ psql_version }}/main"
