---
# vars file for dependencies
common_packages:
  - curl
  - ca-certificates
debian_psql_packages:
  - postgresql-{{ psql_version }}
  - postgresql-contrib
redhat_psql_packages:
  - postgresql{{ psql_version }}-server
psql_conf_folder_path: "/etc/postgresql/{{ psql_version }}/main"
