---
# vars file for repmgr-standby-conf
psql_data_directory_path: "/var/lib/postgresql/{{ psql_version }}/main"
psql_repmgr_conf_path: "/etc/postgresql/{{ psql_version }}/main/repmgr.conf"
psql_bindir_path: "/usr/lib/postgresql/{{ psql_version }}/bin"
psql_scripts_repmgr_path: "/usr/bin"
repmgr_scripts:
  - repmgr-common.sh
  - setup-repmgr.sql
psql_conf_path:
  - /etc/postgresql/{{ psql_version }}/main/postgresql.conf
  - /etc/postgresql/{{ psql_version }}/main/pg_hba.conf
psql_conf_folder_path: "/etc/postgresql/{{ psql_version }}/main"
