---
# tasks file for common
# - name: Prepare Yum repos for Nginx by add nginx.repo file to yum repos folder
#   block:
#     - name: Copy tls.conf file for k3s configuration from templates
#       ansible.builtin.template:
#         src: nginx.repo.j2
#         dest: "{{ yum_repos_path }}/nginx.repo"
#         mode: '0755'
- name: Install Nginx Package Debian OS
  block:
    - name: Update cache
      ansible.builtin.apt:
        update_cache: yes
    - name: Install Nginx Package Debian OS
      ansible.builtin.apt:
        name: "{{ item }}"
        state: present
      with_items: "{{ debian_packages }}"
  when: ansible_facts['os_family'] == "Debian"

- name: Install Nginx Package RedHat OS
  block:
    - name: Update cache
      ansible.builtin.dnf:
        update_cache: yes
    - name: Install Nginx Package RedHat OS
      ansible.builtin.dnf:
        name: "{{ item }}"
        state: present
      with_items: "{{ rhel_packages }}"
  when: ansible_facts['os_family'] == "RedHat"

- name: Install Nginx Package Centos OS
  block:
    - name: Update cache
      ansible.builtin.dnf:
        update_cache: yes
    - name: Install Nginx Package CentOS OS
      ansible.builtin.dnf:
        name: "{{ item }}"
        state: present
      with_items: "{{ centos_packages }}"
  when: ansible_facts['os_family'] == "CentOS"
