---
# tasks file for load-balancer
- name: Prepare Self Sign Certificate scripts and templates
  block:
    - name: Copy load-balancer scripts to the remote host
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: "{{ lb_scripts_path }}"
        owner: root
        group: root
        mode: '0755'
      with_items: "{{ lb_scripts }}"
    - name: Include modules to Nginx configuration
      ansible.builtin.file:
        path: /etc/nginx/load-balancer
        recurse: true
        state: directory
    - name: Copy load-balancer.conf file for k3s configuration from templates
      ansible.builtin.template:
        src: load-balancer.conf.j2
        dest: "{{ load_balancer_conf_path }}/load-balancer.conf"
        mode: '0755'
    - name: Include modules to Nginx configuration
      ansible.builtin.shell: |
        {{ lb_scripts_path }}/nginx_conf.sh {{ nginx_conf_path }}
      args:
        executable: /bin/bash
    - name: Systemd restart Nginx
      become: true
      ansible.builtin.systemd_service:
        name: nginx
        state: restarted
        enabled: true
