// Ubuntu 22.04 ARM64 — golden base image (no tenant, no compliance, no ansible).
//
// STAGE 1 of the two-stage build. This template does ONE thing: produce a
// clean, autoinstalled, ssh-ready Ubuntu 22.04 ARM64 qcow2. Tenant-specific
// hardening is applied in stage 2 (templates/bosch-ubuntu2204-arm64-hardened.pkr.hcl
// and future siblings) by booting THIS image and running ansible against it.
//
// Why split:
//   - Iteration on ansible role bugs becomes ~3 min (boot existing qcow2 +
//     ansible) instead of ~12-15 min (full OS install + ansible).
//   - One base image can feed N tenant variants without re-installing OS.
//   - Failure isolation: install bugs vs hardening role bugs are separable.
// See ADR follow-up "two-stage build" (date TBD) for the design write-up.
//
// Build:
//   STAGE=base ARCH=arm64 ./scripts/build.sh bosch qemu        # qcow2 only
//   STAGE=base ARCH=arm64 ./scripts/build.sh bosch virtualbox  # ova only
//   STAGE=base ARCH=arm64 ./scripts/build.sh bosch all         # both, parallel
// or directly:
//   packer init templates/ubuntu2204-arm64-base.pkr.hcl
//   packer build \
//     -var-file=variables/common.pkrvars.hcl \
//     -var-file=variables/ubuntu-arm64-base.pkrvars.hcl \
//     -var ssh_private_key_file=keys/packer_ed25519 \
//     -only=qemu.ubuntu2204-arm64 \             # or virtualbox-iso.ubuntu2204-arm64
//     templates/ubuntu2204-arm64-base.pkr.hcl
//
// Output:
//   qemu:       output/base/ubuntu2204-arm64/<version>/<image_name_prefix>-<version>.qcow2
//   virtualbox: output/base/ubuntu2204-arm64-vbox/<version>/<image_name_prefix>-<version>.ova
//
// Coupling to the bake-time SSH key:
//   This template injects the public half of keys/packer_ed25519 via cloud-init
//   (http/user-data.tmpl, @@SSH_PUBKEY@@ token). Stage 2 SSHes in with the
//   matching private key. If you regenerate the keypair (delete keys/),
//   re-bake the base — the old base's authorized_keys won't accept new keys.
//   This is intentional: simple, no per-stage key rotation plumbing.

packer {
  required_version = ">= 1.10.0"
  required_plugins {
    qemu       = { source = "github.com/hashicorp/qemu", version = "~> 1.1" }
    // virtualbox source added (Path D) so engineers on Apple Silicon can
    // consume the same hardened image via `vagrant up --provider virtualbox`.
    // Requires VBox 7.1.6+ (current 7.2.x stable) for arm64. Reference:
    // chef/bento ships virtualbox+arm64 Ubuntu 22.04 boxes — same recipe.
    virtualbox = { source = "github.com/hashicorp/virtualbox", version = "~> 1.0" }
  }
}

// ---------- variables ----------

variable "iso_url"             { type = string }
variable "iso_checksum"        { type = string }
variable "ssh_username"        { type = string }
variable "ssh_timeout"         { type = string }
variable "image_version"       { type = string }
variable "image_name_prefix"   { type = string }
variable "output_base_dir"     { type = string }
variable "build_cpus"          { type = number }
variable "build_memory"        { type = number }
variable "disk_size_mb"        { type = number }

// EFI firmware paths — Apple Silicon Homebrew default. Override if your prefix
// differs. See bosch-…-hardened.pkr.hcl for the full rationale on why pflash
// EFI (efi_boot=true + _code/_vars) and not the legacy `firmware = "..."` field.
variable "qemu_efi_firmware" {
  type    = string
  default = "/opt/homebrew/share/qemu/edk2-aarch64-code.fd"
}

variable "qemu_efi_firmware_vars" {
  type    = string
  default = "/opt/homebrew/share/qemu/edk2-arm-vars.fd"
}

// SSH private key path — see header comment for the contract with stage 2.
variable "ssh_private_key_file" {
  type        = string
  description = "Path to the bake-time SSH private key. Generated by build.sh."
}

// ---------- locals ----------

locals {
  // Per-provider output dirs. Keep qemu's path UNCHANGED so existing tooling
  // (build.sh BASE_IMAGE_PATH discovery, latest/ symlinks) keeps working;
  // park VBox in a sibling tree to avoid parent/child output_directory
  // collisions and to keep it visually separable.
  output_dir_qemu       = "${var.output_base_dir}/base/ubuntu2204-arm64/${var.image_version}"
  output_dir_virtualbox = "${var.output_base_dir}/base/ubuntu2204-arm64-vbox/${var.image_version}"

  // Boot command (qemu) — IDENTICAL to the qemu variant in the legacy monolith.
  // Every gotcha (the `e` edit-entry vs `c` interactive shell, three <down>s
  // not two, plain `nocloud` not `nocloud-net`, 10.0.2.2 SLIRP gateway not
  // {{ .HTTPIP }}, Ctrl-X to boot) is documented in the monolith template
  // and the agent-memory feedback files. Do not change without re-reading
  // those — every line cost real debug time.
  boot_command_qemu = [
    "<wait>e<wait2>",
    "<down><wait><down><wait><down><wait><end><wait>",
    " autoinstall ds=\"nocloud;s=http://10.0.2.2:{{ .HTTPPort }}/\"<wait>",
    "<leftCtrlOn>x<leftCtrlOff>",
  ]

  // Boot command (virtualbox) — same GRUB `e` edit-entry pattern as qemu, but
  // the autoinstall URL uses Packer's {{ .HTTPIP }} template var because VBox
  // NAT does NOT expose the host HTTP server at the qemu-style fixed
  // 10.0.2.2 SLIRP gateway. Packer's vbox plugin substitutes the right
  // host-reachable IP. Bento's ubuntu-22.04-aarch64 vbox boot_command
  // confirms this is the working approach for Ubuntu 22.04 ARM64 + VBox.
  //
  // Boot key = <f10> (NOT Ctrl-X). On VBox arm64 the keyboard is USB HID
  // (no PS/2 controller — armv8virtual chipset). USB HID modifier+key
  // sequences (leftCtrlOn ... x ... leftCtrlOff) are timing-fragile during
  // the first few seconds after the kernel attaches the USB stack. Single-
  // keystroke <f10> ("boot from edited entry" in GRUB2) is what chef/bento
  // ships in os_pkrvars/ubuntu/ubuntu-22.04-aarch64.pkrvars.hcl and is the
  // proven path. Cross-checked against bento main 2026-05.
  boot_command_virtualbox = [
    "<wait>e<wait2>",
    "<down><wait><down><wait><down><wait><end><wait>",
    " autoinstall ds=\"nocloud;s=http://{{ .HTTPIP }}:{{ .HTTPPort }}/\"<wait>",
    "<f10><wait>",
  ]
}

// ---------- sources ----------
//
// Two parallel sources off the same Ubuntu 22.04 ARM64 ISO:
//   - qemu source       → output/base/ubuntu2204-arm64/<ver>/<file>.qcow2
//   - virtualbox-iso    → output/base/ubuntu2204-arm64-vbox/<ver>/<file>.ova
//
// They share the same http_directory (cloud-init user-data / meta-data
// served by Packer's built-in HTTP server), the same iso_url / iso_checksum,
// and the same SSH credentials baked into user-data. They differ only in
// hypervisor-specific knobs (firmware path, NAT translation, boot command
// IP) and the GRUB-edit URL pattern (qemu uses fixed SLIRP 10.0.2.2; VBox
// uses Packer's {{ .HTTPIP }} template var).
//
// vmware-iso and parallels-iso bases are still out of scope. Each would
// need its own source block here AND a matching consume-pre-baked-disk
// source at stage 2 (vmware-vmx / parallels-pvm). Add when actively
// consumed by engineers, not before — see chef/bento for canonical
// recipes per (provider, arch).
//
// Build invocation tip: pass `-only=qemu.ubuntu2204-arm64` (or
// `-only=virtualbox-iso.ubuntu2204-arm64`) to bake just one provider.
// Without `-only`, packer runs both in parallel — fine if you have the
// host headroom, but typical workflow is one at a time per arch host.

source "qemu" "ubuntu2204-arm64" {
  iso_url              = var.iso_url
  iso_checksum         = var.iso_checksum
  cpus                 = var.build_cpus
  memory               = var.build_memory
  disk_size            = "${var.disk_size_mb}M"
  format               = "qcow2"
  qemu_binary          = "qemu-system-aarch64"
  accelerator          = "hvf"
  machine_type         = "virt"
  cpu_model            = "host"
  efi_boot             = true
  efi_firmware_code    = var.qemu_efi_firmware
  efi_firmware_vars    = var.qemu_efi_firmware_vars
  http_directory       = "http"
  ssh_username         = var.ssh_username
  ssh_password         = var.ssh_username
  ssh_private_key_file = var.ssh_private_key_file
  ssh_timeout          = var.ssh_timeout
  shutdown_command     = "echo '${var.ssh_username}' | sudo -S /sbin/shutdown -hP now"
  boot_wait            = "10s"
  boot_command         = local.boot_command_qemu
  output_directory     = local.output_dir_qemu
  vm_name              = "${var.image_name_prefix}-${var.image_version}.qcow2"
  // Flip to `true` once the base bake is reliable. While debugging,
  // `false` + cocoa display (below) lets you watch GRUB / installer.
  headless         = true
  net_device       = "virtio-net"
  disk_interface   = "virtio"
  vnc_bind_address = "127.0.0.1"
  vnc_port_min     = 5900
  vnc_port_max     = 5900

  qemuargs = [
    ["-boot", "strict=off"],
    ["-machine", "type=virt,accel=hvf,highmem=on"],
    ["-device", "virtio-net,netdev=user.0"],
    ["-device", "qemu-xhci"],
    ["-device", "usb-kbd"],
    ["-device", "usb-tablet"],
    ["-device", "ramfb"],
    ["-device", "virtio-gpu-pci"],
  ]
}

source "virtualbox-iso" "ubuntu2204-arm64" {
  iso_url      = var.iso_url
  iso_checksum = var.iso_checksum

  // ARM64 essentials.
  //   firmware = "efi" — REQUIRED. Ubuntu 22.04 arm64 won't boot under
  //     VBox's legacy BIOS. Same EFI requirement as qemu source above.
  //   guest_os_type = "Ubuntu_arm64" — canonical bento-confirmed string
  //     for VBox 7.1.6+ ARM64 Ubuntu support. VBox auto-derives sensible
  //     chipset / NIC / storage controller defaults from this.
  firmware      = "efi"
  guest_os_type = "Ubuntu_arm64"

  cpus      = var.build_cpus
  memory    = var.build_memory
  disk_size = var.disk_size_mb // VBox plugin takes plain MB int, not "${n}M"

  http_directory = "http"

  ssh_username         = var.ssh_username
  ssh_password         = var.ssh_username
  ssh_private_key_file = var.ssh_private_key_file
  ssh_timeout          = var.ssh_timeout
  shutdown_command     = "echo '${var.ssh_username}' | sudo -S /sbin/shutdown -hP now"

  boot_wait    = "10s"
  boot_command = local.boot_command_virtualbox

  output_directory = local.output_dir_virtualbox
  // No file extension — VBox plugin appends `.ova` automatically when
  // format = "ova". Setting "<name>.ova" here would produce "<name>.ova.ova".
  vm_name  = "${var.image_name_prefix}-${var.image_version}"
  format   = "ova"
  headless = true

  // Guest Additions has no working arm64 build. Disabling avoids a
  // download/install attempt that would either fail or no-op silently.
  guest_additions_mode = "disable"

  // ARM64 storage uses virtio (no IDE controller present on armv8virtual
  // chipset — see vboxmanage block below for the controller removal).
  hard_drive_interface = "virtio"
  iso_interface        = "virtio"

  // ARM64 hardware wiring — these are LOAD-BEARING on Apple Silicon hosts.
  //
  // Without these, `packer build` fails at "Typing the boot command..." with:
  //   VBoxManage: error: Failed to send a scancode.
  //
  // Why: Packer uses `VBoxManage controlvm <vm> keyboardputscancode` to
  // deliver each boot_command keystroke. That call targets a PS/2 keyboard.
  // VBox's arm64 chipset (`armv8virtual`) has NO PS/2 controller — the
  // default keyboard is unreachable, scancode injection writes into the
  // void, and Packer aborts before the GRUB edit even starts.
  //
  // The fix mirrors chef/bento's working ubuntu-22.04-aarch64 vbox build
  // (packer_templates/pkr-sources.pkr.hcl, aarch64 branch of `vboxmanage`):
  //   --chipset armv8virtual    explicit ARM chipset (some VBox versions
  //                             default to x86 chipset on arm64 hosts → no
  //                             USB stack at all)
  //   --usb-xhci on             enable USB 3.0 controller (required before
  //                             any USB HID device can attach)
  //   --keyboard usb            switch from (absent) PS/2 to USB HID kbd
  //   --mouse usb               same for mouse — needed for the installer
  //                             to capture pointer events
  //   --graphicscontroller      qemu-style ramfb is the only working
  //     qemuramfb               graphics device on arm64 VBox; default is
  //                             unsupported and gives a black VRDP feed
  //   storagectl ... --remove   IDE controller is auto-attached at create
  //     "IDE Controller"        time even on arm64 where it's vestigial.
  //                             Drop it; virtio (above) carries the disks.
  //
  // Cross-referenced against:
  //   https://github.com/chef/bento/blob/main/packer_templates/pkr-sources.pkr.hcl
  //   https://github.com/chef/bento/blob/main/os_pkrvars/ubuntu/ubuntu-22.04-aarch64.pkrvars.hcl
  vboxmanage = [
    ["modifyvm", "{{.Name}}", "--chipset", "armv8virtual"],
    ["modifyvm", "{{.Name}}", "--usb-xhci", "on"],
    ["modifyvm", "{{.Name}}", "--keyboard", "usb"],
    ["modifyvm", "{{.Name}}", "--mouse", "usb"],
    ["modifyvm", "{{.Name}}", "--graphicscontroller", "qemuramfb"],
    ["storagectl", "{{.Name}}", "--name", "IDE Controller", "--remove"],
  ]
}

// ---------- build ----------

build {
  name = "ubuntu2204-arm64-base"
  sources = [
    "source.qemu.ubuntu2204-arm64",
    "source.virtualbox-iso.ubuntu2204-arm64",
  ]

  // NO ansible provisioner here — that's stage 2's job.
  // NO shell provisioner here for tenant config — anything tenant-specific
  // belongs downstream. The shell block below ONLY stamps /etc/base-image-
  // metadata so stage 2 images can prove their lineage to a specific base
  // build. Runs identically against both the qemu and virtualbox sources.
  provisioner "shell" {
    inline = [
      "set -e",
      "echo '${var.ssh_username}' | sudo -S tee /etc/base-image-metadata > /dev/null <<EOF",
      "# Packer-baked Ubuntu 22.04 ARM64 base — stage 1 of two-stage build",
      "base_version=${var.image_version}",
      "base_baked_at=$(date -u +%FT%TZ)",
      "EOF",
      "echo '${var.ssh_username}' | sudo -S chmod 0644 /etc/base-image-metadata",
    ]
  }

  // One manifest per source, parked alongside that source's artifact.
  // `only` filters which source the post-processor runs against so each
  // manifest reflects exactly one build (otherwise both blocks would fire
  // for both sources and overwrite each other).
  post-processor "manifest" {
    only       = ["qemu.ubuntu2204-arm64"]
    output     = "${local.output_dir_qemu}/manifest.json"
    strip_path = true
    custom_data = {
      stage         = "base"
      arch          = "arm64"
      os            = "ubuntu-22.04"
      provider      = "qemu"
      image_version = var.image_version
    }
  }

  post-processor "manifest" {
    only       = ["virtualbox-iso.ubuntu2204-arm64"]
    output     = "${local.output_dir_virtualbox}/manifest.json"
    strip_path = true
    custom_data = {
      stage         = "base"
      arch          = "arm64"
      os            = "ubuntu-22.04"
      provider      = "virtualbox"
      image_version = var.image_version
    }
  }
}
