---
all:
  hosts:
    master1:
      ansible_host: 192.168.10.11
    slave1:
      ansible_host: 192.168.10.21
    slave2:
      ansible_host: 192.168.10.22
  vars:
    psql_version: 15
    citus_version: 11.3
    network_cidr_range: 192.168.10.0/24
  children:
    master:
    slave:

master:
  hosts:
    master1:

slave:
  hosts:
    slave1:
    slave2:
