---
# vars file for common
debian_packages:
  - haproxy
  - rsyslog
  - keepalived
  - psmisc

rhel_packages:
  - haproxy
  - rsyslog
  - keepalived
  - psmisc

centos_packages:
  - haproxy
  - rsyslog
  - keepalived
  - psmisc
