---
# tasks file for impl-config
- name: Ensure the keepalived.conf is overwritten with the correct template
  ansible.builtin.template:
    src: k3s.keepalived.conf.j2
    dest: "{{ keepalive_conf_path }}/keepalived.conf"
    owner: root  # Set file owner (optional)
    group: root  # Set file group (optional)
    mode: '0644'
    force: true
- name: Restart Keepalived service after config update
  become: true
  ansible.builtin.systemd_service:
    name: keepalived
    state: restarted
    enabled: true
