#SPDX-License-Identifier: MIT-0
---
# tasks file for ios

- name: Setup Requirement Packages
  block:
    - name: Update homebrew
      community.general.homebrew:
        update_homebrew: true

    - name: Install Packages
      community.general.homebrew:
        name: "{{ item.name }}"
        force_formula: "{{ item.force_formula }}"
        state: "{{ item.state }}"
      with_items: "{{ packages }}"

    - name: Run basic PowerShell script
      ansible.builtin.shell:
        cmd: |
          git config --global user.email "{{ github_email }}"
          git config --global user.name "{{ github_user }}"

          git config --global core.autocrlf false
          git config --global core.filemode false
          git config --global core.fscache true
          git config --global core.preloadindex true
          git config --global depot-tools.allowGlobalGitConfig false
          git config --global http.sslVerify false
          git config --global https.sslVerify false
          git config --global http.postBuffer 1048576000 # 1GB
          git config --global http.lowSpeedLimit 0
          git config --global http.lowSpeedTime 999999
          git config --global safe.directory E:/actions-runner/_work/herond-browser/herond-browser
          git config --global safe.directory '*'
      args:
        chdir: "/Users/{{ ansible_user }}"
        executable: /bin/bash

- name: Setup Build Key
  block:
    - name: Copy scripts to the remote host
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: "/Users/{{ ansible_user }}"
        owner: "{{ ansible_user }}"
        mode: '0755'
      with_items: "{{ provision_profiles }}"

- name: Configure NVM And Setup NodeJS
  block:
    - name: Copy scripts to the remote host
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: "{{ scripts_path }}"
        owner: "{{ ansible_user }}"
        mode: '0755'
      with_items: "{{ scripts }}"

    - name: Install NVM and setup NodeJS
      ansible.builtin.shell:
        cmd: "/bin/bash -c '{{ scripts_path }}/{{ item }}'"
      args:
        chdir: "/Users/{{ ansible_user }}"
        executable: /bin/bash
      with_items: "{{ scripts }}"

- name: Copy Apple Certificates To Remote Host
  block:
    - name: Create provision profiles dir
      ansible.builtin.shell: |
        mkdir -p {{ apple_certificates_path }}
      args:
        chdir: "/Users/{{ ansible_user }}"
        executable: /bin/bash

    - name: Copy scripts to the remote host
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: "{{ apple_certificates_path }}"
        owner: "{{ ansible_user }}"
        mode: '0755'
      with_items: "{{ apple_certificates }}"

    - name: Create provision profiles dir
      ansible.builtin.shell: |
        security unlock-keychain -p "{{ ansible_password }}" ~/Library/Keychains/login.keychain-db

        # Import certificate
        security import {{ item }} \
          -k ~/Library/Keychains/login.keychain-db \
          -P "{{ p12_password }}" \
          -T /usr/bin/codesign \
          -T /usr/bin/security \
          -T /usr/bin/xcodebuild

        # Set permissions
        security set-key-partition-list -S apple-tool:,apple: -s \
        -k "{{ ansible_password }}" ~/Library/Keychains/login.keychain-db
      args:
        chdir: "{{ apple_certificates_path }}"
        executable: /bin/bash
      with_items: "{{ apple_certificates }}"

- name: Setup Provision Profiles
  block:
    - name: Create provision profiles dir
      ansible.builtin.shell: |
        mkdir -p {{ provision_profiles_path }}
      args:
        executable: /bin/bash

    - name: Copy scripts to the remote host
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: "{{ provision_profiles_path }}"
        owner: "{{ ansible_user }}"
        mode: '0755'
      with_items: "{{ provision_profiles }}"

- name: Setup Build Key
  block:
    - name: Create provision profiles dir
      ansible.builtin.shell: |
        mkdir -p {{ build_key_path }}
      args:
        executable: /bin/bash

    - name: Copy scripts to the remote host
      ansible.builtin.copy:
        src: "KEY.p8"
        dest: "{{ build_key_path }}"
        owner: "{{ ansible_user }}"
        mode: '0755'

- name: Install XCode
  block:
    - name: Install XCode
      ansible.builtin.shell: |
        softwareupdate --install
      args:
        executable: /bin/bash
