---
- name: k3s-dependencies-install
  hosts: all
  become: true
  become_user: root
  tasks:
    - name: Ping all nodes
      ansible.builtin.ping:
  roles:
    - role: ../../roles/k3s/common/dependencies
    - role: ../../roles/k3s/common/kennel-config

---
- name: k3s-setup
  hosts: server
  become: true
  become_user: root
  serial: 1
  tasks:
    - name: Ping all nodes
      ansible.builtin.ping:
  roles:
    - role: ../../roles/k3s/server/server-register # k3s Server Register

    - role: ../../roles/k3s/load-balancer/haproxy/common
    - role: ../../roles/k3s/load-balancer/haproxy/self-signed-cert
    - role: ../../../../roles/k3s/load-balancer/haproxy/impl-config

    - role: ../../../../roles/k3s/load-balancer/keepalived/common
    - role: ../../roles/k3s/load-balancer/keepalived/impl-config
    - role: ../../roles/k3s/agent/agent-register
