# Bosch / prod / vault / proxmox — VMs on company Proxmox cluster.

all:
  children:
    vault_server:
      hosts:
        bosch-vault-pve-[1:3]:
          ansible_host: "10.43.22.{{ 10 + (inventory_hostname | regex_search('[0-9]+$') | int) }}"
  vars:
    proxmox_api_host: pve.bosch.internal       # TODO
    proxmox_node: pve01                         # TODO
    proxmox_storage: ceph-pool                  # TODO
