---
all:
  hosts:
    master1:
      ansible_host: 0.0.0.0
      ansible_port: 2751
    slave1:
      ansible_host: 0.0.0.0
      ansible_port: 2761
    slave2:
      ansible_host: 0.0.0.0
      ansible_port: 2762
  vars:
    psql_version: 15
    citus_version: 11.3
    server_ip: 192.168.10.11
    server_cidr_range: 192.168.10.0/24
    docker_network_cidr_range: 172.20.10.0/24
    docker_default_cidr_range: 172.17.0.0/16

  children:
    master:
    slave:

master:
  hosts:
    master1:

slave:
  hosts:
    slave1:
    slave2:

repmgr:
  hosts:
    master1:
    # slave1:
    # slave2:
