---
# vars file for server-register
k3s_server_scripts:
  - server-register.sh
psql_k3s_url: "postgres://{{ hostvars['server-1']['psql_k3s_user'] }}:{{ hostvars['server-1']['psql_k3s_pass'] }}@${{ hostvars['server-1']['psql_k3s_url'] }}/k3s"
