---
# tasks file for citus-configuration
- name: Install Citus
  block:
    - name: Add Citus repository for package manager
      ansible.builtin.shell: |
        curl https://install.citusdata.com/community/deb.sh | bash
      args:
        executable: /bin/bash
    - name: Install PostgreSQL Citus packages
      ansible.builtin.apt:
        name: "{{ item }}"
        state: present
      with_items: "{{ psql_packages }}"

- name: Configure Citus
  block:
    - name: Copy citus scripts to the remote host
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: "{{ psql_scripts_citus_path }}"
        owner: vagrant
        group: vagrant
        mode: '0755'
      with_items: "{{ citus_scripts }}"
    - name: Citus config script for master
      vars:
        trigger_sql_func: create-distribute-table-func.sql
      ansible.builtin.shell:
        cmd: "bash -c '{{ psql_scripts_citus_path }}/citus-conf.sh {{ psql_version }} {{ psql_scripts_citus_path }}/{{ trigger_sql_func }}'"
      args:
        chdir: /var/lib/postgresql
        executable: /bin/bash
    - name: Systemd restart PostgreSQL
      become: yes
      ansible.builtin.systemd_service:
        name: postgresql
        state: restarted
        enabled: true
    - name: Citus setup connect script for master
      ansible.builtin.shell:
        cmd: "bash -c '{{ psql_scripts_citus_path }}/citus-connect.sh {{ private_ip }} {{ citus_dbname }} {{ slave_ips | join(' ') }}'"
      args:
        chdir: /var/lib/postgresql
        executable: /bin/bash
      when: "'master' in ansible_hostname"
  when: "'replica' not in ansible_hostname"
