---
- name: k3s-server-register-setup
  hosts: server
  become: true
  become_user: root
  serial: 1
  tasks:
    - name: Ping all nodes
      ansible.builtin.ping:
  roles:
    - role: ../../roles/k3s/server/server-register
