# Bosch / dev / vault / proxmox — single-node Vault VM for dev/test.

all:
  children:
    vault_server:
      hosts:
        bosch-vault-dev-pve-1:
          ansible_host: 10.43.42.11
  vars:
    proxmox_api_host: pve.bosch.internal       # TODO
    proxmox_node: pve02                         # TODO
    proxmox_storage: local-zfs                  # TODO
